In [8]:
import backtrader as bt
import backtrader.indicators as btind
import datetime
import pandas as pd
import pickle
import math
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import sys
sys.path.append('../lib/')
from makeKospi200Data import *

In [9]:
start_test = '2017-01-01'
start_validation = '2018-03-30'
end_date = '2018-03-30'
code = '201'
pickle_path = '..\\dataOutput\\'

In [10]:
with open(pickle_path + 'ADA-2018-04-09-9-13_model_for_backtest.pickle', 'rb') as f:
        clf = pickle.load(f)

model = clf['model']

win_K   = clf['win_K']
win_CCI = clf['win_CCI']
win_R   = clf['win_R']
lag      = clf['lag']
RSI_span = clf['RSI_span']
win_ma   = clf['win_ma']
method   = clf['method']

In [11]:
X_train, X_test, X_validation, y_train, y_test, y_validation \
    = make_data(end_date, start_test, start_validation, code, win_K, win_CCI, win_R, lag, RSI_span, win_ma)

X_test.index = pd.to_datetime(X_test.index)

In [12]:
X_train.tail(10)

,open,high,low,close,volume,returns,%K,%D,slow%D,ADO,CCI,%R,MACD,momentum,ROC,RSI,SMA,WMA
date,,,,,,,,,,,,,,,,,,
2016-12-16,261.59,262.91,261.16,262.56,60475,-0.002399,96.927129,92.440208,92.488036,0.834286,122.800522,8.177570,2.198296,10.42,104.132625,74.455002,259.538,259.807725
2016-12-19,262.03,263.22,261.86,261.93,46955,0.002520,88.974359,91.155875,91.984155,0.485294,109.387185,37.941176,2.237486,6.30,102.464499,68.933285,260.517,260.193593
2016-12-20,262.78,263.26,262.14,262.59,51200,-0.001866,94.293015,93.398168,92.331417,1.187500,99.058040,19.476744,2.292386,6.25,102.438168,71.488279,261.213,260.629303
2016-12-21,263.76,264.42,262.10,262.10,62168,-0.000496,82.015504,88.427626,90.993890,0.788793,88.922217,50.434783,2.270446,0.10,100.038168,66.781773,261.789,260.896703
2016-12-22,262.71,262.92,261.66,261.97,53376,-0.001374,76.821192,84.376570,88.734121,0.650794,65.765045,53.260870,2.216440,1.06,100.406270,65.462450,261.786,261.091848
2016-12-23,262.10,262.26,261.30,261.61,46535,0.001109,66.784870,75.207189,82.670462,0.302083,48.930690,61.086957,2.120335,0.89,100.341362,61.575506,261.856,261.186057
2016-12-26,261.83,262.27,261.36,261.90,45262,0.002253,56.476684,66.694249,75.426003,0.725275,42.223557,77.300613,2.042486,0.27,100.103199,63.584086,261.974,261.315865
2016-12-27,262.35,262.85,261.79,262.49,52535,-0.010629,58.043478,60.435011,67.445483,0.896226,42.177722,61.858974,2.002894,0.49,100.187023,67.565005,262.060,261.529344
2016-12-28,259.65,260.59,259.52,259.70,54257,0.001194,3.673469,39.397877,55.509046,-1.775701,1.711089,96.326531,1.733652,-1.75,99.330656,42.316686,261.830,261.196736
2016-12-29,259.02,260.04,258.62,260.01,48685,0.001346,23.965517,28.560822,42.797903,0.239437,-7.935545,76.034483,1.526686,-2.55,99.028793,44.953221,261.686,260.980966

In [13]:
y_test

date
2017-01-02    1.0
2017-01-03    1.0
2017-01-04   -1.0
2017-01-05    1.0
2017-01-06    1.0
2017-01-09   -1.0
2017-01-10    1.0
2017-01-11    1.0
2017-01-12   -1.0
2017-01-13   -1.0
2017-01-16    1.0
2017-01-17   -1.0
2017-01-18    1.0
2017-01-19   -1.0
2017-01-20    1.0
2017-01-23    1.0
2017-01-24    1.0
2017-01-25    1.0
2017-01-26   -1.0
2017-01-31    1.0
2017-02-01   -1.0
2017-02-02    1.0
2017-02-03    1.0
2017-02-06   -1.0
2017-02-07   -1.0
2017-02-08   -1.0
2017-02-09    1.0
2017-02-10    1.0
2017-02-13   -1.0
2017-02-14    1.0
             ...
2018-01-15    1.0
2018-01-16   -1.0
2018-01-17   -1.0
2018-01-18    1.0
2018-01-19   -1.0
2018-01-22    1.0
2018-01-23   -1.0
2018-01-24    1.0
2018-01-25    1.0
2018-01-26    1.0
2018-01-29   -1.0
2018-01-30   -1.0
2018-01-31   -1.0
2018-02-01   -1.0
2018-02-02   -1.0
2018-02-05   -1.0
2018-02-06   -1.0
2018-02-07    1.0
2018-02-08   -1.0
2018-02-09    1.0
2018-02-12    1.0
2018-02-13    1.0
2018-02-14    1.0
2018-02-19   -1.0
2018-02-20    1.0
2018-02-21   -1.0
2018-02-22    1.0
2018-02-23    1.0
2018-02-26   -1.0
2018-02-27   -1.0
Name: Direction, Length: 282, dtype: float64

In [14]:
market_code = '201'
fromdate = datetime(2017,1,1)
todate   = datetime(2017,6,30)
KOSPI200 = pd.read_sql("SELECT * from marketcandle where code= {} and date between '{}' \
                        and '{}'".format(market_code, fromdate, todate), con=engine, index_col=["date"])
KOSPI200['openinterest'] = 0
KOSPI200.drop(['code'], axis=1,inplace=True);

In [15]:
pred = model.predict(X_test);pred

array([ 1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,
       -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1.,
        1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
        1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  0.,  1.,  1., -1.,
        1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,  1., -1., -1., -1.,
       -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
        1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,
        1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
        1., -1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,
        1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,  1., -1., -1.,
        1.,  1.,  1.,  1., -1., -1.,  1., -1., -1., -1., -1., -1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1.,
       -1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1., -1.,
       -1., -1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
       -1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,
        1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
       -1., -1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,
        1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1., -1.,  1.,  1., -1., -1.])

In [16]:
len(pred)

282

In [17]:
hit_rate = (sum(pred == y_test))/len(pred)

In [18]:
hit_rate

1.0